### ISSUE TITLE
Format for modellen?

### ISSUE THREAD

**Issue by losolio** [hdir/Tillitsrammeverk#1]
Prøvde å åpne modellen i Archi 5.2, men fikk en del feilmeldinger. Hvilket format/versjon er modellene lagret i?

<img width="677" alt="image" src="https://github.com/hdir/Tillitsrammeverk/assets/17168367/c80b482b-fd2a-4ef5-9338-081089540924">

**Comment by xivind** [comment]
Archi versjon 5.2 burde fungere. Jeg bruker 5.2, og alt i orden der. Men du trenger en plugin til Archi for at dette skal fungere. Man kan ikke åpne Archi-filer direkte fra repoet, slik du ville åpnet lokale archi-filer, det må skje gjennom menyvalgene i plugin. Plugin kan lastes ned her https://www.archimatetool.com/plugins/ , den heter coArchi – Model Collaboration for Archi. Bare gi beskjed til @thomiz  eller meg om du trenger hjelp til å sette den opp.

**Comment by losolio** [comment]
Takker!

**Comment by losolio** [comment]
@xivind sendte en PR for framtidige undrende sjeler her #2

**Comment by xivind** [comment]
> @xivind sendte en PR for framtidige undrende sjeler her #2

Det var en veldig god ide @losolio Dette gjelder egentlig alle repositorier vi har med Archi-plugin. Overlater til @thomiz å gjøre merge på PRen din.
